INSERT INTO activities
  (weather_type, activity_type, hi_temp, low_temp, activity_name, activity_description)
VALUES 
  ('Clear','Social',40,18,'Paint Fight','Fill up balloons with (hopefully non-toxic) paint and have a war.'),
  ('Clear','Leisure',40,18,'No Pool? No Problem','Cover a trampoline in water and soap, then slide around on it.'),
  ('Clear','Nature',40,10,'Visit the Zoo','Go to the zoo and try to guess what all the animals are thinking about.'),
  ('Clouds','Nature',40,10,'Visit the Zoo','Go to the zoo and try to guess what all the animals are thinking about.'),
  ('Snow','Nature',40,10,'Visit the Zoo','Go to the zoo and try to guess what all the animals are thinking about.'),
  ('Clear','Buy/Sell',40,18,'Have a Yard Sale','Gather all your old stuff together and have a yard sale. Then split the profits and spend it all on ice cream or something.'),
  ('Clouds','Leisure',25,18,'Go to a Park', 'Go to the playground at a park and swing on the swings, as long as you are still young enough for that to not be creepy.'),
  ('Clouds','Social',25,18,'Pool Party!','Have a pool party without a pool. Everyone can just sit in the living room with swim suits and goggles.'),
  ('Clear','Social',25,18,'Pool Party!','Have a pool party without a pool. Everyone can just sit in the living room with swim suits and goggles.'),
  ('Clouds','Event',25,18,'Celebrate Something','Have a parade with just you walking down the street playing a kazoo. Maybe have your dog in there too.'),
  ('Clouds','Social',25,18,'Pac-Tag','Dress as Pac-Man, get 4 friends dressed up as ghosts, and play tag in a public place.'),
  ('Rain','Photography',18,12,'Take pictures','Seriously, terrible weather makes for some great photo opportunities!'),
  ('Rain','Family Fun',18,12,'Go for a walk and jump in the puddles','You’ll need good rubber boots, a raincoat and a child-like sense of fun.'),
  ('Rain','Social',18,12,'Break out of an escape room','Escape rooms are becoming more popular by the minute. You’ll definitely have an awesome time (unless you fail and get trapped for all eternity).'),
  ('Rain','Relax',18,12,'80s/Disney & Chill','Have a movie marathon with Disney movies or 80s movies or even 80s Disney movies.'),
  ('Clear','Relax',18,12,'80s/Disney & Chill','Have a movie marathon with Disney movies or 80s movies or even 80s Disney movies.'),
  ('Clouds','Relax',18,12,'80s/Disney & Chill','Have a movie marathon with Disney movies or 80s movies or even 80s Disney movies.'),
  ('Snow','Relax',18,12,'80s/Disney & Chill','Have a movie marathon with Disney movies or 80s movies or even 80s Disney movies.'),
  ('Drizzle','Relax',18,12,'80s/Disney & Chill','Have a movie marathon with Disney movies or 80s movies or even 80s Disney movies.'),
  ('Snow','Social',10,1,'Make Snow Day Margaritas + Play Games','Put some of that beautiful white fluff to good use — in your margarita glass. Sip your snowy concoction, and get out a puzzle or board game.'),
  ('Snow','Food',10,1,'Midnight Pancakes','Go to your friends house at midnight and make pancakes with them.'),
  ('Clear','Food',10,1,'Midnight Pancakes','Go to your friends house at midnight and make pancakes with them.'),
  ('Clouds','Food',10,1,'Midnight Pancakes','Go to your friends house at midnight and make pancakes with them.'),
  ('Clouds','Food',10,1,'Hangry','DEMOLISH EVERYTHING'),
  ('Rain','Food',10,1,'Midnight Pancakes','Go to your friends house at midnight and make pancakes with them.'),
  ('Snow','Arts & Crafts',10,1,'Tackle That DIY Project','Uninterrupted free time means it’s time to get out your DIY supplies.'),
  ('Snow','Family Fun',10,1,'Do Glacial Graffiti',' Fill several spray bottles with water and food coloring and your yard will be a shoo-in for best dressed on the block.'),
  ('Thunderstorm','Gaming',15,11,'Video Game Tournament','Have a video game tournament to see who is the best at first person shooters, fighting games, and Tetris.'),
  ('Thunderstorm','Food',15,11,'Bake Something','Type ingredients you already have in your kitchen into a recipe generator and cook or bake something.'),
  ('Thunderstorm','Arts & Crafts',15,11,'Power out?','Draw pictures in total darkness and see how they turn out.'),
  ('Thunderstorm','Learn',15,11,'Learn YouTube', 'Look at YouTube videos and say to yourself I can do a video way better than these people. Then do it.'),
  ('Drizzle','Exercise',18,12,'Go for a Jog','Try to run for a really long time like Forrest Gump but then stop after maybe a block or two.'),
  ('Drizzle','Nature',18,12,'Appreciate Nature','Scream at a tree. It deserves to know that you acknowledge its hard work and dedication to the environment.'),
  ('Mist','Volunteer',18,12,'Stab Things','Volunteer in your community by becoming one of those garbage stabber people.'),
  ('Mist','Buy/Sell',18,12,'Shop Local','Go to a store and buy only three things and see who can creep the cashier out the most with them.'),
  ('Apocolypse','Survive',999,234,'Loot!','Steal stuff and things!'),
  ('Apocolypse','Survive',999,234,'Zombies?','Wear light-weight chainmail to keep from being bitten and have a samurai sword. And hoard toilet paper for currency.'),
  ('Apocolypse','Survive',999,234,'Stock up','Everyone always jokes that Twinkies could survive the apocalypse. Put that theory to the test by stocking up'),
  ('Apocolypse','Survive',999,234,'Become a Pirate','Gather food and supplies (maybe some other survivors) and head out to sea.');